### ISSUE TITLE
Change GraphEditorProperties custom properties

### ISSUE THREAD

**Issue by eckig** [tesis-dynaware/graph-editor#14]
I would like to request a change for the GraphEditorProperties custom properties from a normal `java.util.Map` to a `javafx.collections.ObservableMap` so we may register change listeners on the custom properties and react accordingly.

**Comment by rmfisher** [comment]
Pushed the changes, they'll be included in the next release.

Sorry about the slow response, I'm still on holiday :)

**Comment by eckig** [comment]
No problem, enjoy the rest of your holidays ;)
