### ISSUE TITLE
Node properties for custom display

### ISSUE THREAD

**Issue by DaRich** [tesis-dynaware/graph-editor#15]
For customizing nodes with skins it would be great if there was the possibility to add custom properties to a Node. With a map provided one could simply render custom JavaFX nodes which need additional parameters.

**Comment by rmfisher** [comment]
Just to clarify - you would like the GNode class to have properties? Or the skin class?

**Comment by DaRich** [comment]
The GNode class so that I can use the properties in the skin class for custom rendering.

**Comment by eckig** [comment]
There is no need for that. You should probably create a domain model and connect it to the graph model, as described here: https://github.com/tesis-dynaware/graph-editor/wiki/4.%20Connecting%20to%20Domain%20Models

This API works a bit different than the usual JavaFX components, but it works quite nicely ;-)

**Comment by rmfisher** [comment]
Yes, so the idea is that there is some other domain model 'behind' your graph, and that this model could store such information.

I'm not totally opposed to adding a properties map, if a good case can be made for it. But please read the page linked above first and see if it meets your needs.

**Comment by DaRich** [comment]
You are right. If I had access to the domain model the Issue could be closed.
But how can I access my class from the EMF domain model in `GNodeSkin`?

**Comment by rmfisher** [comment]
This is not something we have worked through ourselves yet, so it is quite likely that the current API has room for improvement (issue [#6](https://github.com/tesis-dynaware/graph-editor/issues/6) for example).

But perhaps you could do something like this?
```java
Commands.addNode(model, node);
MyCustomSkinClass skin = (MyCustomSkinClass) graphEditor.getSkinLookup().lookupNode(node);
skin.setDomainReference(domainObject);
```
After you create a new node, you get the skin instance and set your domain model reference in it.

**Comment by DaRich** [comment]
Thank you for your answer!
Does not matter if the current API is smooth or not. With this approach I can get my properties, so I will close the issue.

Thank you for sharing your great work!

**Comment by DaRich** [comment]
I post an abstract of my solution if you are interested. It uses the `CommandStack` for searching the corresponding domain object by using the `GNode` of `GNodeSkin` as a key. This is not very nice, because the command list in `BasicCommandStack` is `protected`, but it could by solved by inheritance.
