### ISSUE TITLE
Add GNodeSkin dispose method

### ISSUE THREAD

**Issue by eckig** [tesis-dynaware/graph-editor#20]
Please add a `dispose` method to the `GNodeSkin` class so we can do a proper cleanup when the skin is no longer used.

Maybe even retrofit the class to implements the `Skin` interface? (https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Skin.html)

**Comment by rmfisher** [comment]
I added a dispose method to all skin classes. It's called on the skin after it's JavaFX node is removed from the view.

I can't implement the Skin interface, as the model classes like GNode aren't Skinnable.

**Comment by eckig** [comment]
Regarding the `Skin` interface: I realized it a few moments after I openened this issue. Just came to my mind, because they are quite similar.

But thanks again for implementing it on such a short notice ;-)
