### ISSUE TITLE
Make "GraphEditorContainer.getChildren()" public

### ISSUE THREAD

**Issue by eckig** [tesis-dynaware/graph-editor#23]
As the title reads.. please increase the visibility of `GraphEditorContainer.getChildren()` to `public`.

We need this modifiable List of children to add additional overlays similar to the already existing minimap.

Yes, we could add/remove these overlays on a different Node above (additional layer) but this increases complexity and makes it hard to manage different overlays.

**Comment by rmfisher** [comment]
Sounds reasonable. I exposed it but haven't tested adding other children yet so no guarantees it will work properly :)

**Comment by eckig** [comment]
Alread did this, with reflection (which is always kind of ugly) and it works just fine. So thanks for adding a proper way of doing this.
