### ISSUE TITLE
GNode from Connection

### ISSUE THREAD

**Issue by NHS247** [tesis-dynaware/graph-editor#27]
Hi,

Is it posible to get the Node attached to a joint on a connection from the API

 graphEditor.getModel().getConnections().stream().forEach(gConnection -> {
// here I get can get joints but it seems not possible to get the source and target  GNodes?
 });

**Comment by eckig** [comment]
Each `GConnection` has a source and a target `GConnector` which has a method `getParent()` which returns the `GNode`

**Comment by NHS247** [comment]
Thanks! - perfect
