### ISSUE TITLE
How to add content to Node 

### ISSUE THREAD

**Issue by stooray1** [tesis-dynaware/graph-editor#31]
I want to add class diagram or some graphics with string  to nodes. I am looking  for some time however, so far no success. is there any example?

**Comment by rmfisher** [comment]
Check the "titled" skin example in the demo. E.g. the createContent() method in this class:

[TitledNodeSkin.java](https://github.com/tesis-dynaware/graph-editor/blob/master/demo/src/main/java/de/tesis/dynaware/grapheditor/demo/customskins/titled/TitledNodeSkin.java)

By the way this project is no longer maintained.

**Comment by stooray1** [comment]
Thanks for your reply. This example is helpful.
