### ISSUE TITLE
GJoint Positions while moving GNode(s)

### ISSUE THREAD

**Issue by eckig** [tesis-dynaware/graph-editor#8]
The current approach places GJoint(s) absolutely in the graph editor.
When moving the GNodes where the corresponding GConnections connectors are attached to, the GJoints do not move accordingly and will eventually get behind a node.

Wouldn't it be better to place the GJoints relatively instead of absolutely?
One solution could be to place the GJoints with Bindings?
Or another solution, if you want to stick with absolute positioning, would be to adjust the GJoint positions if they get into / behind other nodes?

**Comment by eckig** [comment]
This won't be fixed?

**Comment by rmfisher** [comment]
No, I don't see any solution that is transparent to the user. I would prefer to keep it simple. If you want the joints to be bound to the source node and move with it, you will have to implement this yourself. The current skins do not distinguish graphically between what the source and target nodes are, so it would be very confusing.
